cargo-features = ["profile-rustflags", "trim-paths"]

[package]
name = "mangahub-spellchecker"
description = "This crate is deprecated. Use SpelRight instead. A fast and lightweight spell checker and suggester."
version = "0.3.1"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/Zefirchiky/SpelRight"

[dependencies]
rayon = "1.11.0"

[profile.dev]
incremental = true
rustflags = ["-Zthreads=8"]

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
trim-paths = "all" # Removes potentially privileged information from binaries.
rustflags = ["-Cdebuginfo=0"] # Better compile performance.

[dev-dependencies]
criterion = "0.7.0"
